---
- name: Install Docker on private instances
  hosts: private_instances
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Run NGINX container
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"
